### ISSUE TITLE
extra junk added to data when read from kinesis

### ISSUE THREAD

**Issue by crodwell** [a8m/kinesis-producer#9]
Hi, it appears that as I'm writing JSON using this package that it may be adding extra data and I can't trace the source.  

for example 
`payload := []byte("{\"test\": \"me\"}")`
`Pr.Put(payload, "11111111-1111-1111-1111-111111111122")`

If i consume the stream with the AWS CLI, and base64decode ASCII the data field, I get the following string:

`$11111111-1111-1111-1111-111111111122{"test": "me"}iTDu	Z`

**Comment by a8m** [comment]
Hey @crodwell,
This producer sends messages in the Kinesis aggregation format that used by the [KPL]. In order to de-aggregate these messages, you need to use the [KCL]. I don't think the AWS CLI has this capability. 

I'm going to close this issue, since there's not bug or problem here. Feel free to open if you have any other question or problem. 

[KPL]: https://docs.aws.amazon.com/streams/latest/dev/developing-producers-with-kpl.html
[KCL]: https://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-kcl.html

**Comment by crodwell** [comment]
Thanks @a8m !  That'll be it :)
